### ISSUE TITLE
Support pathname-based routing

### ISSUE THREAD

**Issue by arthur-xavier** [slamdata/purescript-routing#26]
I believe that this library could also support pathname-based routing, which would, in turn, allow for its use on server-side rendering (for isomorphic/universal applications).

**Comment by arthur-xavier** [comment]
Closing this as I just saw in the guide:
```
This library facilitates hash-based routing. If you're looking to do pushstate routing with the history object, then you are in the wrong place.
```

**Comment by mohanzhang** [comment]
@arthur-xavier Did you end up settling for hash-based routing or did you find an alternative?
