### ISSUE TITLE
Match an exact url

### ISSUE THREAD

**Issue by boothead** [slamdata/purescript-routing#30]
There doesn't seem to be a way to say that you want to match only a certain string (like eof in attoparsec). Have I missed something, or is this the case and by design?

**Comment by garyb** [comment]
I think you're right that it's not possible, but not by design, just accident :smile:

**Comment by throughnothing** [comment]
I just ran into the same thing.  Would be nice to have an `end` match, or similar.  Pux does this in their routing [here](https://github.com/alexmingoia/purescript-pux/blob/fcb82bab7013d9c6b1d7faf30055698b91b968db/src/Pux/Router.purs#L45).

**Comment by throughnothing** [comment]
I've put together a possible solution [here](https://github.com/slamdata/purescript-routing/pull/36), would love to hear your thoughts.
