### ISSUE TITLE
Rename `matchHash` and `matchHash'`

### ISSUE THREAD

**Issue by menelaos** [slamdata/purescript-routing#32]
The [guide](https://github.com/slamdata/purescript-routing/blob/master/GUIDE.md) mentions that this library only supports hash-based routing. The actual matching, however, is completely agnostic to where it gets the URL string from:
```purescript
matchHash :: forall a. Match a -> String -> Either String a
matchHash' :: forall a. (String -> String) -> Match a -> String -> Either String a
```
I would thus propose to drop the `Hash` part and rename the above two functions into `match` and either `match'` or `matchWith`. If you approve of this, I will open a PR later today.

**Comment by garyb** [comment]
`match` and `matchWith` sounds good to me 👍
