### ISSUE TITLE
add documentation in README, examples, and tests

### ISSUE THREAD

**Issue by jdegoes** [slamdata/purescript-routing#5]

**Comment by parsonsmatt** [comment]
I'm looking at how y'all are using the routing in the slamdata app and trying to piece where it all comes together. I can see that the routes are defined [like this](https://github.com/slamdata/slamdata/blob/f1ea77fd2a5257114162cdda80c9a9bb9ba8efcf/src/Driver/Notebook/Routing.purs#L39-L48) and [this](https://github.com/slamdata/slamdata/blob/f1ea77fd2a5257114162cdda80c9a9bb9ba8efcf/src/Driver/File/Routing.purs#L32-L52), and [this is where the routing function gets called](https://github.com/slamdata/slamdata/blob/f08b0da823e1951e16966f067742528803464118/src/Driver/File.purs#L72). I can't quite figure out it all ties in [here](https://github.com/slamdata/slamdata/blob/d8931bd2a64edd07c5e98f737bf56257da33e56f/src/Entries/File.purs#L38-L40) though.

I'd definitely like to use this in an app I am planning to build, and would be happy to write up a good introductory tutorial in the process :D I think if I could just get a little nudge in how the routes tie in to the halogen components then I'd be set.

**Comment by jdegoes** [comment]
Hey Matt, that'd be awesome! You can ping @cryogenian in the gitter.im/slamdata/slamdata chat room, and he should be able to give you a nudge or two. :smile:

**Comment by parsonsmatt** [comment]
Ok! I've got something worked up. The draft post is [here](https://github.com/parsonsmatt/parsonsmatt.github.io/blob/routing/_posts/2015-10-22-purescript_router.markdown). I'd appreciate any feedback or input y'all might have.

One thing I'm definitely curious about is if there's a better way to write the `redirects` function for a parent component:

```purescript
redirects :: forall eff. Driver QueryP eff
          -> Maybe Routes
          -> Routes
          -> Aff (Effects eff) Unit
redirects driver _ Home = 
  driver (Coproduct (Left (action (Goto Home))))
redirects driver _ Profile =
  driver (Coproduct (Left (action (Goto Profile))))
redirects driver _ (Sessions view) =
  driver (Coproduct (Left (action (Goto (Sessions view)))))

```

It's not too bad with a `driver <<< Coproduct <<< Left <<< action <<< Goto`, but it feels like there should be a less direct way to encode that.

**Comment by garyb** [comment]
You can use `left` from `Data.Functor.Coproduct` to avoid the need for `Coproduct (Left ...`, but apart from that I think you have to do what you have here.

**Comment by jdegoes** [comment]
@parsonsmatt Wow, nice work on that post!

@garyb I feel like maybe prisms and `purescript-totally` should help here. Albeit it'd probably be more code unless you have that type of matching in multiple places.

**Comment by parsonsmatt** [comment]
Awesome, `left` is an improvement :smile:

**Comment by jasonzoladz** [comment]
@jdegoes 

I've found the library very useful, but it was bit difficult to get started with it.  So I just put in a pull request that adds this [guide](https://github.com/jasonzoladz/purescript-routing/blob/master/GUIDE.md).  Edit as you see fit.
