### ISSUE TITLE
Update guide for v7

### ISSUE THREAD

**Issue by ravloony** [slamdata/purescript-routing#52]
Would it be possible to update the Pursuit documentation, and the guide in this repository to version 7? It's difficult to work with no documentation, and we don't want to use version 5 because we know it is already obsolete.

Thanks!

**Comment by garyb** [comment]
Hey, I've pushed the new docs, but I'm not entirely sure what has changed in the recent versions so not sure what changed the guide needs. Hopefully someone who knows better can pick that up. :wink:
