### ISSUE TITLE
Generalize `Routing.Match` combinators

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-routing#54]
I don't think any of these need to be monomorphic and can instead be defined in terms of `MatchClass`.

**Comment by garyb** [comment]
`eitherMatch` would have to be added to the class I think, or the constraint on the class would have to be strengthened.

Alternative proposal too: we get rid of the class and only have the monomorphic versions 🙂

**Comment by natefaubion** [comment]
How is `eitherMatch` different than `either fail pure`? I agree that the class is unnecessary.

**Comment by natefaubion** [comment]
Same with `optionalMatch`. How is it different than `map Just a <|> pure Nothing`?

**Comment by garyb** [comment]
`optionalMatch` is fine, I'm not sure I understand how `either fail pure` works though? You need to `bind`, hence my comment about the constraint.

**Comment by natefaubion** [comment]
Oh I see, yes you are right. We should just remove the class. I don't see what we gain from using it.

**Comment by garyb** [comment]
Resolved in the 0.12 branch
